/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package montador;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author kevin
 */
public class tela extends javax.swing.JFrame {
    
    public static String ArquivoCarregado = new String("") ;
    protected static DefaultListModel<String> listIntermediarioModel = new DefaultListModel<>();
    protected static DefaultListModel<String> symbolTableModel = new DefaultListModel<>();
    protected static DefaultListModel<String> listSaidaModel = new DefaultListModel<>();
    /**
     * Creates new form tela
     */
    public tela() {
        initComponents();
        montador.print_simbolos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        codigoFonteLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListIntermediario = new javax.swing.JList<>();
        codigoFonteLabel = new javax.swing.JLabel();
        codigoFonteLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListSaida = new javax.swing.JList<>();
        ButtonPrimeiraPassagem = new javax.swing.JButton();
        carregarArquivoButton = new javax.swing.JButton();
        buttonSegundaPassagem = new javax.swing.JButton();
        codigoFonteLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListSimbolos = new javax.swing.JList<>();
        codigoFonteLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListSegmentos = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1047, 600));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        codigoFonteLabel2.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel2.setText("Codigo Fonte");
        codigoFonteLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jScrollPane4.setViewportView(jListIntermediario);

        codigoFonteLabel.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel.setText("Codigo Intermediario");
        codigoFonteLabel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        codigoFonteLabel1.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel1.setText("Codigo Saida");
        codigoFonteLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane3.setViewportView(jListSaida);

        ButtonPrimeiraPassagem.setText("Primeira Passagem");
        ButtonPrimeiraPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPrimeiraPassagemActionPerformed(evt);
            }
        });

        carregarArquivoButton.setText("Carregar arquivo");
        carregarArquivoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarArquivoButtonActionPerformed(evt);
            }
        });

        buttonSegundaPassagem.setText("Segunda Passagem");
        buttonSegundaPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSegundaPassagemActionPerformed(evt);
            }
        });

        codigoFonteLabel4.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel4.setText("Tabela de Simbolos");
        codigoFonteLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane6.setViewportView(jListSimbolos);

        codigoFonteLabel3.setBackground(new java.awt.Color(0, 0, 0));
        codigoFonteLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigoFonteLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoFonteLabel3.setText("Tabela de Segmentos");
        codigoFonteLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane5.setViewportView(jListSegmentos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonPrimeiraPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carregarArquivoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSegundaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(codigoFonteLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(codigoFonteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoFonteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoFonteLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoFonteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(carregarArquivoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPrimeiraPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonSegundaPassagem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoFonteLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigoFonteLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(746, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void carregarArquivoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
                                                                                        // Carrega código fonte para interface e para variavel arquivoCarregado
        String linha = new String();
        //System.out.println("teste = " + System.getProperty("user.dir"));
        String CaminhoDoArquivo = new String(System.getProperty("user.dir")+"/src/main/java/montador/entrada.txt");
        BufferedReader buffRead; //reader do arquivo
        
        try {
            buffRead = new BufferedReader(new FileReader(CaminhoDoArquivo));
                  
            linha = buffRead.readLine();
            while (linha!=null) {                
                ArquivoCarregado = ArquivoCarregado.concat(linha+"\n");
                linha= buffRead.readLine();
            }
            jTextArea.setText(ArquivoCarregado);

            buffRead.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                     

    private void ButtonPrimeiraPassagemActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        try{                                                                               // Carrega código fonte e transforma em intermediario
            montador.primeira_passagem();
            System.out.println("Button actioned ");
            jListIntermediario.setModel(listIntermediarioModel);
            jListSimbolos.setModel(symbolTableModel);
        } catch(IOException e){ 
            System.out.println("Erro 404: " + e.getMessage());
        }
    }                                                      

    private void buttonSegundaPassagemActionPerformed(java.awt.event.ActionEvent evt) {                                                      
                                                                                            //Carrega código intermediario e transforma em final
        String linha = new String();
        //System.out.println("teste = " + System.getProperty("user.dir"));
        String CaminhoDoArquivo = new String(System.getProperty("user.dir")+"/src/main/java/montador/firstPass.txt");
        BufferedReader buffRead; //reader do arquivo
        ArquivoCarregado = "";
    
        try {
            buffRead = new BufferedReader(new FileReader(CaminhoDoArquivo));
                  
            linha = buffRead.readLine();
            while (linha!=null) {                
                ArquivoCarregado = ArquivoCarregado.concat(linha+"\n");
                linha = buffRead.readLine();
            }
            buffRead.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            montador.segunda_passagem();
            System.out.println("Button actioned ");
            jListSaida.setModel(listSaidaModel);
        } catch(IOException e){ 
            System.out.println("Erro 404: " + e.getMessage());
        }
    }                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ButtonPrimeiraPassagem;
    private javax.swing.JButton buttonSegundaPassagem;
    private javax.swing.JButton carregarArquivoButton;
    private javax.swing.JLabel codigoFonteLabel;
    private javax.swing.JLabel codigoFonteLabel1;
    private javax.swing.JLabel codigoFonteLabel2;
    private javax.swing.JLabel codigoFonteLabel3;
    private javax.swing.JLabel codigoFonteLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListIntermediario;
    private javax.swing.JList<String> jListSaida;
    private javax.swing.JList<String> jListSegmentos;
    private javax.swing.JList<String> jListSimbolos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration                   
}
